services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tcsdb
      POSTGRES_USER: tcs
      POSTGRES_PASSWORD: tcs
    ports:
      - "5432:5432"
    volumes:
      - ./db-init/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tcs -d tcsdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql+psycopg2://tcs:tcs@db:5432/tcsdb
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: db+postgresql+psycopg2://tcs:tcs@db:5432/tcsdb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  airflow-init:
    image: apache/airflow:2.9.3
    depends_on:
      db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "this_is_a_demo_secret_keep_it_same_everywhere"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.2.3"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    entrypoint: /bin/bash
    command: -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      airflow-init:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "this_is_a_demo_secret_keep_it_same_everywhere"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.2.3"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: [ "airflow", "scheduler" ]

  airflow-webserver:
    image: apache/airflow:2.9.3
    depends_on:
      airflow-init:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: "this_is_a_demo_secret_keep_it_same_everywhere"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas==2.2.3"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: [ "airflow", "webserver" ]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # UI
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build: ./api
    command: [ "celery", "-A", "app.celery_app:celery", "worker", "--loglevel=INFO", "--concurrency=1" ]
    environment:
      DATABASE_URL: postgresql+psycopg2://tcs:tcs@db:5432/tcsdb
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: db+postgresql+psycopg2://tcs:tcs@db:5432/tcsdb
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
